[package]
name = "orb-fleet-cmdr"
version = "0.1.0"
description = "Worldcoin Fleet Commander"
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
const_format = "0.2.30"
figment = { version = "0.10.8", features = ["env", "toml"] }
futures.workspace = true
libc.workspace = true
listenfd = "1.0.0"
once_cell = "1.15.0"
orb-build-info.workspace = true
orb-endpoints.workspace = true
orb-telemetry.workspace = true
orb-relay-client.workspace = true
orb-relay-messages.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_path_to_error = "0.1.8"
serde_with = "3.11.0"
tap = "1.0.1"
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
tokio-stream.workspace = true
tokio-util.workspace = true
tracing = { workspace = true, features = ["attributes"] }
zbus = { workspace = true, default-features = false, features = ["tokio"] }
zbus_systemd = { workspace = true, features = ["systemd1", "login1"] }

[build-dependencies]
orb-build-info = { workspace = true, features = ["build-script"] }

[dev-dependencies]
dbus-launch = "0.2.0"
tokio = { workspace = true, features = ["sync", "test-util"] }

[package.metadata.deb]
maintainer-scripts = "debian/"
assets = [["target/release/orb-fleet-cmdr", "/usr/local/bin/", "755"]]
systemd-units = [{ unit-name = "worldcoin-fleet-cmdr" }]
